flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/api/routes.py
from flask import Blueprint, jsonify, request
from flaskblog.models import Post, User, Menu,  Hotel, Kamar, Transaksi, UserSchema, PostSchema, MenuSchema, HotelSchema, KamarSchema, TransaksiSchema, db, ma
from flask_login import login_required, current_user

api = Blueprint('api', __name__)
menu_schema = MenuSchema(strict=True)
menus_schema = MenuSchema(many=True, strict=True)
kamar_schema = KamarSchema(strict=True)
kamars_schema = KamarSchema(many=True, strict=True)
hotel_schema = HotelSchema(strict=True)
hotels_schema = HotelSchema(many=True, strict=True)
user_schema = UserSchema(strict=True)
users_schema = UserSchema(many=True, strict=True)
post_schema = PostSchema(strict=True)
posts_schema = PostSchema(many=True, strict=True)
transaksi_schema = TransaksiSchema(strict=True)
transaksis_schema = TransaksiSchema(many=True, strict=True)


########################################################################
############################# G E T ####################################
########################################################################

@api.route("/api/menu", methods=['GET'])
def menu():
	menu = Menu.query.all()
	result = menus_schema.dump(menu)
	return jsonify(result.data)

@api.route("/api/hotel", methods=['GET'])
def hotel():
	hotel = Hotel.query.all()
	result = hotels_schema.dump(hotel)
	return jsonify(result.data)

@api.route("/api/kamar", methods=['GET'])
def kamars():
	kamar = Kamar.query.all()
	result = kamars_schema.dump(kamar)
	return jsonify(result.data)

@api.route("/api/kamar/<id>", methods=['GET'])
def kamar(id):
	kamar = Kamar.query.get(id)
	return kamar_schema.jsonify(kamar)


@api.route("/api/user/<id>", methods=['GET'])
def user(id):
	user = User.query.get(id)
	return user_schema.jsonify(user)

@api.route("/api/user/all", methods=['GET'])
def users():
	all_user = User.query.all()
	result = users_schema.dump(all_user)
	return jsonify(result.data)

@api.route("/api/post/<user_id>", methods=['GET'])
def post(user_id):
	posts = Post.query.filter_by(user_id=user_id)
	result = posts_schema.dump(posts)
	return jsonify(result.data)

@api.route("/api/post/all", methods=['GET'])
def posts():
	all_post = Post.query.all()
	result = posts_schema.dump(all_post)
	return jsonify(result.data)

@api.route("/api/transaksi/<id>", methods=['GET'])
def transaksi(id):
	transaksi = Transaksi.query.get(id)
	return transaksi_schema.jsonify(transaksi)

@api.route("/api/transaksi/all", methods=['GET'])
def transaksis():
	all_transaksi = Transaksi.query.all()
	result = transaksis_schema.dump(all_transaksi)
	return jsonify(result.data)

########################################################################
########################### P O S T ####################################
########################################################################

@api.route('/api/menu/add', methods=['POST'])
def add_menu():
	menu = request.json['menu']
	keterangan = request.json['keterangan']
	image_file = request.json['image_file']

	new_menu = Menu(menu, keterangan, image_file)

	db.session.add(new_menu)
	db.session.commit()

	return menu_schema.jsonify(new_menu)

@api.route('/api/kamar/add', methods=['POST'])
def add_kamar():
	nama = request.json['nama']
	image_file = request.json['image_file']
	fasilitas = request.json['fasilitas']
	harga = request.json['harga']
	stok = request.json['stok']

	new_kamar = Menu(nama,image_file,fasilitas,harga,stok)

	db.session.add(new_kamar)
	db.session.commit()

	return kamar_schema.jsonify(new_kamar)

@api.route('/api/hotel/add', methods=['POST'])
def add_hotel():
	nama = request.json['nama']
	alamat = request.json['alamat']
	image_file = request.json['image_file']

	new_hotel = Menu(nama, alamat, image_file)

	db.session.add(new_hotel)
	db.session.commit()

	return hotel_schema.jsonify(new_hotel)

@api.route('/api/user/add', methods=['POST'])
def add_user():
	username = request.json['username']
	email = request.json['email']
	image_file = request.json['image_file']
	password = request.json['password']

	new_user = Menu(menu, email, image_file ,password)

	db.session.add(new_user)
	db.session.commit()

	return user_schema.jsonify(new_user)

@api.route('/api/post/add', methods=['POST'])
def add_post():
	title = request.json['title']
	date_posted = request.json['keterangan']
	content = request.json['content']
	user_id = request.json['user_id']

	new_post = Menu(title, date_posted, content, user_id)

	db.session.add(new_post)
	db.session.commit()

	return post_schema.jsonify(new_post)

@api.route('/api/transaksi/add', methods=['POST'])
def add_transaksi():
	user = request.json['user']
	kamar = request.json['kamar']
	harga = request.json['harga']
	start_from = request.json['start_from']
	hari = request.json['hari']
	phone = request.json['phone']
	email = request.json['email']
	total = request.json['total']

	new_transaksi = Transaksi(user, kamar, harga, start_from, hari, phone, email, total)

	db.session.add(new_transaksi)
	db.session.commit()

	return transaksi_schema.jsonify(new_transaksi)


########################################################################
############################# P U T ####################################
########################################################################

@api.route('/api/menu/edit/<id>', methods=['PUT'])
def edit_menu(id):
	menu = Menu.query.get(id)

	new_menu = request.json['menu']
	keterangan = request.json['keterangan']
	image_file = request.json['image_file']

	menu.menu = new_menu
	menu.keterangan = keterangan
	menu.image_file = image_file

	db.session.commit()

	return menu_schema.jsonify(menu)

@api.route('/api/kamar/edit/<id>', methods=['PUT'])
def edit_kamar(id):
	kamar = Kamar.query.get(id)

	nama = request.json['nama']
	image_file = request.json['image_file']
	fasilitas = request.json['fasilitas']
	harga = request.json['harga']
	stok = request.json['stok']

	kamar.nama = nama
	kamar.image_file = image_file
	kamar.fasilitas = fasilitas
	kamar.harga = harga
	kamar.stok = stok

	db.session.commit()

	return kamar_schema.jsonify(kamar)

@api.route('/api/hotel/edit/<id>', methods=['PUT'])
def edit_hotel(id):
	hotel = Hotel.query.get(id)
	nama = request.json['nama']
	alamat = request.json['alamat']
	image_file = request.json['image_file']

	hotel.nama = nama
	hotel.alamat = alamat
	hotel.image_file = image_file

	db.session.commit()

	return hotel_schema.jsonify(hotel)

@api.route('/api/user/edit/<id>', methods=['PUT'])
def edit_user(id):
	user = User.query.get(id)
	username = request.json['username']
	email = request.json['email']
	image_file = request.json['image_file']
	password = request.json['password']

	user.username = username
	user.email = email
	user.image_file = image_file
	user.password = password

	db.session.commit()

	return user_schema.jsonify(user)

@api.route('/api/post/edit/<id>', methods=['PUT'])
def edit_post(id):
	post = Post.query.get(id)
	title = request.json['title']
	date_posted = request.json['keterangan']
	content = request.json['content']
	user_id = request.json['user_id']

	post.title = title
	post.date_posted = date_posted
	post.content = content
	post.user_id = user_id

	db.session.commit()

	return post_schema.jsonify(post)

@api.route('/api/transaksi/edit/<id>', methods=['PUT'])
def edit_transaksi(id):
	transaksi = Transaksi.query.get(id)
	user = request.json['user']
	kamar = request.json['kamar']
	harga = request.json['harga']
	start_from = request.json['start_from']
	hari = request.json['hari']
	phone = request.json['phone']
	email = request.json['email']
	total = request.json['total']

	transaksi.user = user
	transaksi.kamar = kamar
	transaksi.harga = harga
	transaksi.start_from = start_from
	transaksi.hari = hari
	transaksi.phone = phone
	transaksi.email = email
	transaksi.total = total

	db.session.commit()

	return transaksi_schema.jsonify(transaksi)

########################################################################
########################## D E L E T E #################################
########################################################################

@api.route('/api/menu/delete/<id>', methods=['DELETE'])
def delete_menu(id):
	menu = Menu.query.get(id)
	db.session.delete(menu)
	db.session.commit()

	return menu_schema.jsonify(menu)

@api.route('/api/kamar/delete/<id>', methods=['DELETE'])
def delete_kamar(id):
	kamar = Kamar.query.get(id)
	db.session.delete(kamar)
	db.session.commit()

	return kamar_schema.jsonify(kamar)

@api.route('/api/hotel/delete/<id>', methods=['DELETE'])
def delete_hotel(id):
	hotel = Hotel.query.get(id)
	db.session.delete(hotel)
	db.session.commit()

	return hotel_schema.jsonify(hotel)

@api.route('/api/user/delete/<id>', methods=['DELETE'])
def delete_user(id):
	user = User.query.get(id)
	db.session.delete(user)
	db.session.commit()

	return user_schema.jsonify(user)

@api.route('/api/post/delete/<id>', methods=['DELETE'])
def delete_post(id):
	post = Post.query.get(id)
	db.session.delete(post)
	db.session.commit()

	return post_schema.jsonify(post)

@api.route('/api/transaksi/delete/<id>', methods=['DELETE'])
def delete_transaksi(id):
	transaksi = Transaksi.query.get(id)
	db.session.delete(transaksi)
	db.session.commit()

	return transaksi_schema.jsonify(transaksi)

flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post, User
from flask_login import login_required

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

@main.route("/api")
@login_required
def api():
    return render_template('api.html', title='Api')

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post berhasil dibuat!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Post berhasil di updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post berhasil di hapus!', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Akun berhasil dibuat! Sekarang kamu bisa log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login gagal. Tolong check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Akun anda telah berhasil di updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Password kamu berhasil di updated! Sekarang kamu bisa log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

flaskblog/templates/api.html
{% extends "layout.html" %}
{% block content %}   
<div>
	<div>
		<h1>API Page</h1>
	</div>
        <article class="content-section">
            <h3>Menu API</h3>
        	<div class="embed-responsive embed-responsive-21by9">
            	<iframe class="embed-responsive-item" src="{{ url_for('api.menu') }}"></iframe>
        	</div>
            <a class="btn btn-outline-primary mt-4 mb-2 mt-4 mb-2" href="{{ url_for('api.menu')}}">See API In Full Page</a>
        </article>
	<div>
        <article class="content-section">
            <h3>Hotel API</h3>
    		<div class="embed-responsive embed-responsive-21by9">
            	<iframe class="embed-responsive-item" src="{{ url_for('api.hotel') }}"></iframe>
        	</div>
    	    <a class="btn btn-outline-primary mt-4 mb-2" href="{{ url_for('api.hotel')}}">See API In Full Page</a>
        </article>
    </div>
    <div>
        <article class="content-section">
            <h3>Kamar API</h3>
            <div class="embed-responsive embed-responsive-21by9">
                <iframe class="embed-responsive-item" src="{{ url_for('api.kamars') }}"></iframe>
            </div>
            <a class="btn btn-outline-primary mt-4 mb-2" href="{{ url_for('api.kamars')}}">See API In Full Page</a>
        </article>
    </div>
    <div>
        <article class="content-section">
            <h3>Users API</h3>
            <div class="embed-responsive embed-responsive-21by9">
                <iframe class="embed-responsive-item" src="{{ url_for('api.users') }}"></iframe>
            </div>
            <a class="btn btn-outline-primary mt-4 mb-2" href="{{ url_for('api.users')}}">See API In Full Page</a>
        </article>
    </div>
    <div>
        <article class="content-section">
            <h3>Posts API</h3>
            <div class="embed-responsive embed-responsive-21by9">
                <iframe class="embed-responsive-item" src="{{ url_for('api.posts') }}"></iframe>
            </div>
            <a class="btn btn-outline-primary mt-4 mb-2" href="{{ url_for('api.posts')}}">See API In Full Page</a>
        </article>
    </div>
    <div>
        <article class="content-section">
            <h3>Transaksis API</h3>
            <div class="embed-responsive embed-responsive-21by9">
                <iframe class="embed-responsive-item" src="{{ url_for('api.transaksis') }}"></iframe>
            </div>
            <a class="btn btn-outline-primary mt-4 mb-2" href="{{ url_for('api.transaksis')}}">See API In Full Page</a>
        </article>
    </div>
</div>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

  {% if title %}
  <title>Flask Blog - {{ title }}</title>
  {% else %}
  <title>Flask Blog</title>
  {% endif %}
</head>

<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">Flask Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">Buat Post Baru</a>
            <a class="nav-item nav-link" href="{{ url_for('main.api') }}">Api</a>
            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Keluar</a>
            {% else %}
            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Masuk</a>
            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Daftar</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
      </div>
      <div class="col-md-4">
        <div class="content-section">
          <h3>Random Sidebar</h3>
          <p class='text-muted'>You can put any information here you'd like.
            <ul class="list-group">
              <a class="list-group-item btn btn-outline-primary" href="{{ url_for('main.home') }}">Latest Posts</a>
              {% if current_user.is_authenticated %}
              <a class="list-group-item btn btn-outline-primary" href="{{ url_for('api.menu') }}">Menu API</a>
              <a class="list-group-item btn btn-outline-primary" href="{{ url_for('api.hotel') }}">Hotel API</a>
              <a class="list-group-item btn btn-outline-primary" href="{{ url_for('api.kamars') }}">Kamar API</a>
              {% endif %}
            </ul>
          </p>
        </div>
      </div>
    </div>
  </main>


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>
</body>

</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Lupa Password?</a>
            </small>
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up sekarang</a>
    </small>
</div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}